# Generated by Django 5.0.14 on 2026-08-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="earns",
            options={"verbose_name_plural": "Earns"},
        ),
        migrations.AlterModelOptions(
            name="learns",
            options={"verbose_name_plural": "Learns"},
        ),
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name_plural": "Ratings"},
        ),
        migrations.AlterModelOptions(
            name="teaches",
            options={"verbose_name_plural": "Teaches"},
        ),
    ]
