# Generated by Django 5.0.14 on 2026-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_earns_options_alter_learns_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
