# Generated by Django 5.0.14 on 2026-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
