# Generated by Django 5.0.14 on 2026-09-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.skill'),
        ),
    ]
